[package]
name = "friendly-chess"
version = "0.2.0"
authors = ["Hieu <hieunguyen.0527@gmail.com>"]
edition = "2018"
description = "friendly neighborhood chess engine"
license = "MIT"

[dependencies]
thiserror = "1.0.44"

